nota1 = float(input("Informe a 1° nota: "))
nota2 = float(input("Informe a 2° nota: "))
soma = (nota1+nota2)
print("A soma das notas é de:",soma)
media = (soma/2)
print("A média das notas é de:",media)