print("Escreva um programa que recebe dois numeros e mostra o maior")
print("\n")
n1 = int(input("Informe o 1° número: "))
n2 = int(input("Informe o 2° número: "))
n3 = int(input("Informe o 3° número: "))
print("O maior número informado é:",max(n1,n2,n3))